### ISSUE TITLE
Sprint 0

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#102]
Epic for Sprint 0

**Comment by jermnelson** [comment]
Sprint 0 Goals
- [ ] Build shared understanding of architecture, make some technical decisions
  - [ ] 3 different back-end models, tech implications, Christina needs dev input
  - [ ] Technology that dept can support
- [ ] Technology that can work in project timeline
 - [ ] Set-up development environments
 - [ ] AWS, Editor Dev, ??
 - [ ] Continuous integration, testing
 - [ ] Documentation practices
- [ ] Investigate profile editor development
 - [ ] What features need to be added (already ticketed)
 - [ ] How easy or not is it to add these?
 - [ ] Back-up plan if not easy?
- [ ] Investigate profile editor deployment
   - [ ] Can we use Circle-CI 
  - [ ] Docker
    - [x] Dockerfile Open WIP PR [#2](https://github.com/LD4P/profile-edit/pull/2)
    - [ ]  Docker-compose using Verso container 
  - [ ] AWS ECS, or does this need a simpler approach
  - [ ] Back-up plan if not feasible (i.e. dedicated, hacky VM?)

- [ ] Stretch: 
 - [ ] Outline in Sinopia Editor Code repo start of libraries / modules

**Comment by jermnelson** [comment]
Will do!
