### ISSUE TITLE
SC #4: Search and view data converted by Casalini Share-VDE (and data from other QA sources)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#106]
Need ability to search Share-VDE data (and other external data accessible via QA) for purposes of copying a description to start a new description (aka derive/deriving). The deriving part is ticketed separately as https://github.com/LD4P/sinopia/issues/95. (Linking to Share-VDE works from lookup fields is different and was part of Release 1.0 https://github.com/LD4P/sinopia/issues/92)

The most important external sources for searching (in order to derive) are Share-VDE and Discogs, but we want to design it so that in future, other QA sources could be searched in the same way.

In priority order:
- [x] search a single institution's Share-VDE dataset from Search tab (parent of #255)
- [ ] search all cohort members' Share-VDE datasets together (parent of #256)
- [x] search Discogs source (parent of #257)
- [ ] add descriptive text to UI to explain how the searching works (wildcards? typeahead? what fields are being searched?) (parent of LD4P/sinopia_editor#1259)
- [x] display extended context of QA sources (parent of LD4P/sinopia_editor#1693)

VIEWING DATA
- What does the success criteria mean by "view'? We can't easily "open" a Share-VDE description because it won't match a Resource Template (that's what "deriving" is about; see #95) So we give the user any more information than what we display in the search results list, without having to "open" the item? Show a mouseover with more information?Let user click the QA URL to go see additional statements?

OUT OF SCOPE
- search additional QA sources beyond Share-VDE and Discogs
- search multiple QA sources of your choosing, at the same time
- search Sinopia and QA sources at the same time
- fielded search, or searching anything beyond what QA indexes

**Comment by michelleif** [comment]
need specs from casalini? when?

**Comment by michelleif** [comment]
in today's QA/Sinopia meeting the topic came up: why aren't we showing extended context for Search tab matches that come from QA? @justinlittman do we have an issue to add this extended context? @astridu do you have a design for showing this on Search tab?

**Comment by astridu** [comment]
I did this a while ago: https://invis.io/2XTVOZ1KPJM#/383489304_External_Data_Source_Results

**Comment by michelleif** [comment]
@astridu isn't there additional context from QA besides type and data source? @justinlittman can we ticket showing extended context for non-Sinopia sources?

**Comment by astridu** [comment]
I don't know. Who could I ask?

**Comment by michelleif** [comment]
closing this because we declared it done for the work cycle, and the undone parts are documented in separate tickets.
