### ISSUE TITLE
Sprint 1

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#114]
- [ ]  Remaining Sprint 0
  - [x] Fixing Coveralls [#51](https://github.com/LD4P/sinopia_profile_editor#51)
  - [ ] Docker Image in CI [#22](https://github.com/LD4P/sinopia_profile_editor#22) (docker image works again [#74](https://github.com/LD4P/sinopia_profile_editor#74))
- [x] AWS, Editor Dev, ?? [#8](https://github.com/LD4P/sinopia_profile_editor#8) 
   - [x] our Docker image as tagged release to DockerHub, probably as part of CI (done manually, not part of CI yet) [#60](https://github.com/LD4P/sinopia_profile_editor#60)
   - [x] Set-up local AWS/ECs development environments/mocks [#16](https://github.com/LD4P/sinopia/issues/16)
      - [x] uses our docker image [#62](https://github.com/LD4P/sinopia_profile_editor#62)
  - [x]  Devs pair w/Rob for terraform 
   - [x] set up load balancer
- [ ] Sinopia Landing Page  
- [ ] Small UI and functionality changes done to Profile Editor (M1T2)
  - [x]  Tests for existing functionality that we are using [#49]( https://github.com/LD4P/sinopia_profile_editor/issues/49), [#50](https://github.com/LD4P/sinopia_profile_editor/issues/50), [#51](https://github.com/LD4P/sinopia_profile_editor/issues/51), [#52](https://github.com/LD4P/sinopia_profile_editor/issues/52)
  - [ ] User-facing Design in [#89]( https://github.com/LD4P/sinopia/issues/89) in priority order
  - [ ] Make Profile Author a required Profile property  [#10](https://github.com/LD4P/sinopia_profile_editor/issues/10)
  - [ ] Make Profile Source an optional profile property [#8](https://github.com/LD4P/sinopia_profile_editor/issues/9) 
  - [ ] disable save and delete buttons in profile editor [#4](https://github.com/LD4P/sinopia_profile_editor/issues/4), [#3](https://github.com/LD4P/sinopia_profile_editor/issues/3)
- [x] README documentation current in sinopia_profile_editor ([#70](https://github.com/LD4P/sinopia_profile_editor#70), [#71](https://github.com/LD4P/sinopia_profile_editor#71))
- [ ] README documentation current in sinopia_editor 

Stretch Goal:
- [ ] Outline Code Structure in Sinopia Editor Code repo, start of libraries / modules [#6](https://github.com/LD4P/sinopia_editor/issues/6)
