### ISSUE TITLE
Sprint 2

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#118]
## Sprint 2 goals

- [ ] **Sinopia Landing Page**
  - [ ]  Finish design (branding, layout done) : copyright
  - [x]  Astrid present design to users
- [ ] I**ntegration Testing of BFE for Sinopia Editor**
  - [ ] Setup, fixures, and Verso mocking 
  - [x] Editor tab
  - [ ] Modals
  - [ ] Look-up Functionality with Mocks
  - [ ]  Preview
  - [ ] Browse
- [ ] **Start Code Structure in Sinopia Editor Code repo**, start of libraries / modules [#6](https://github.com/LD4P/sinopia_editor/issues/6)
  - [ ]  Break down `bfe.js` into discrete components
  - [ ] Stubs for new code (see 
https://docs.google.com/drawings/d/1AeO7_UqecQoPGgrDIdsfTJi6_PRkHnldqHRIbfP8ZCo/edit)  
- [x] **Begin on-boarding the rest of the development team**
- [x] **Discussions with Library of Congress (Jeremy)**
- [ ]  **Finalize Docker images for Profile Editor CI and Production**

## Stretch Goals (know most will be put off to Sprint 3)
- [ ] **Sinopia Landing Page**
  - [ ]  Get html and css to wherever it needs to live  
- [ ] **Sinopia Profile Editor**
  - [x]  Finish first UI and functionality pass
  - [x]  Cherry-pick upstream LoC changes, particular support for default values
  - [ ]  Begin functional acceptance testing
- [ ]  **Finalize Docker images for BF editor CI and Production**

**Comment by jermnelson** [comment]
- [ ]  Finalize Docker images for CI and Production
- [ ] Sinopia Profile Editor
- [ ] Integration Testing of BFE for Sinopia Editor 
- [ ] Begin on-boarding the rest of the development team
- [ ] Discussions with Library of Congress
