### ISSUE TITLE
Sprint 4 goal

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#130]
- [ ]  **Achieve Milestone 1**, Sinopia.io website up and alive, doesn't need to implement all of Astrid's design.
- [x]  **Deploy to AWS with Terraform**
  - [x] Dev env
  - [x] Stage/UAT
  - [x] Manual process if CD not available
- [x] **Sinopia Profile Editor**
  - [x]  Bug fixes
  - [x]  Begin Functional Acceptance Testing
-  [x] **Sinopia Landing Page**
   - [x]  Implement React-based CSS and HTML for Homepage
-  [x] **Backend Sinopia Server Work**
   - [x]  Decision on trellis

## Stretch
- [ ] **Begin Integration Testing of BFE for Sinopia Editor**
  - [ ] Setup, fixures, and Verso mocking 
  - [ ] Modals
  - [ ] Look-up Functionality with Mocks
  - [ ]  Preview
  - [ ] Browse
- [ ] **Start Code Structure in Sinopia Editor Code repo**, start of libraries / modules [#6](https://github.com/LD4P/sinopia_editor/issues/6)
  - [ ]  Break down `bfe.js` into discrete components
  - [ ] Stubs for new code (see 
https://docs.google.com/drawings/d/1AeO7_UqecQoPGgrDIdsfTJi6_PRkHnldqHRIbfP8ZCo/edit)
