### ISSUE TITLE
Sprint 5

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#132]
- [x] **Milestone 1 - Deploy homepage to sinopia.io**
  - [x] Finish React Components for Homepage
  - [x]  Setup AWS for homepage deployment
- [ ] Sinopia Server - 
  - [ ] Trellis support on AWS using Docker
  - [x] Decide if Profiles can be stored with LDP syntax
  - [x] Decide if Trellis can be used for User management
  - [ ] Update Swagger spec for Sinopia Server
- [x] Sinopia Editor - Decomposing `bfe.js` focusing on Profile parsing and management
  - [x]  Can profile parsers and management be decomposed into separate components?
  - [x] Decide on a initial code structure 
  - [x]  What tests would be necessary for new components? All new components require unit tests to merged into master. 
  - [x]  Should we continue down decomposing existing bfe codebase or completely new editor code possibly using something like RoR? Our approach is building a "new" React-based node.js application with bfe codebase being incorporated as needed. 
## Stretch goals
- [ ]  Browse and Editor Tab React Stubs
   - [ ] Browse tab has simple search to tie to QA
   - [ ] Editor tab with an **Import a Profile** button
