### ISSUE TITLE
Sprint 8

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#141]
## Sinopia Editor
- [ ] React Components for Resource Templates and input forms
   - [x] Finish Modal handling (when property Template needs another resource Template)
   - [x] Display an entire Profile with different types of form input fields (single, multiple, default values, buttons to modals...)
   - [x] For Input Type Literal Add integration test #212
   - [x] Updated `props` for React Components based on `resourceTemplate` design consensus
   - [ ] Styling for inputs 
- [x]  Check for more recent templates from LC 
- [x] Time bound exploration of [Redux](https://redux.js.org/)
- [x] Editor with an **Import a Profile** button

## Sinopia Profile Editor
- [x] Support any Profiles/resourceTemplate designs updates

## Sinopia Server
- [x] Trellis running on AWS connecting to Amazon RDS
- [ ] Sinopia Server overview for team
- [x] Formal Swagger spec for client-server interactions
- [ ] Profile and `resourceTemplates` JSON  to the Sinopia Server's Trellis

## Stretch Goals
- [x] Users and Authentication in Sinopia
- [ ]  Browse and Editor Tab React Stubs
   - [ ] Browse tab has simple search form stub,
   - [ ] Simple search supports QA 
   - [ ] Display Results following UIX design
