### ISSUE TITLE
Sprint 9

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#142]
## Sinopia Editor
- [x] Finish `resourceTemplates` JSON v2 and BFF exemplar RDF
- [ ] Address any issues as part of Milestone 2
  - [ ] Test QA search of Casalini if available by end of sprint
  - [x] Remove InputLiteral #245
- [x] Redux support for `InputLookups`
- [x] Continue development of `resourceTemplates` RDF generation
- [x]  @atz terraform knowledge transfer

## Sinopia Profile Editor
- [x]  @atz terraform knowledge transfer
- [x] Add additional support for QA lookup

## Sinopia Server
- [x]  @atz terraform knowledge transfer
- [ ] Implementing`resourceTemplates` JSON  to the Sinopia Server's Trellis
- [ ] Sinopia Server overview for team

## Stretch Goals
- [ ] Cognito support w/Terraform
- [ ] Validate `resourceTemplates`
    - [ ] BFF 
    - [ ] Profile editor
    - [ ] Server
- [ ]  Browse and Editor Tab React Stubs
   - [ ] Browse tab has simple search form stub,
   - [ ] Simple search supports QA 
   - [ ] Display Results following UIX design
