### ISSUE TITLE
Sprint 10

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#145]
## Christina Knowledge Transfer
- [x] Sinopia Server Trellis
  - [x] Should Trellis be available to the world? Do we need a "middleware" between Trellis and the outside? 
  - [x] Ideas regarding interactions between Profile Editor, Editor, and Trellis for resourceTemplates
    - [x] creating a new resourceTemplate ... unique id creation in PE - manual?
    - [x] associating URL with resourceTemplate for retrieval (for re-editing in PE or for use as template in BFF)
    - [x ] a resourceTemplate refers to another resourceTemplate :
         -  [x] How does this work in PE?  for new resourceTemplate referring to existing?  referring to not yet written resourceTemplate?   for existing resourceTemplate ...
         - [x] How does this work in BFF?
- [x] Sinopia Architecture documentation

##  Cognito support
- [ ] Using Terraform (knowledge transfer will happen 1/25)
  - Linked Data Editor Issues (BFF)
  -  Sinopia Server Issues
     [#25 Setting up AWS Cognito](https://github.com/LD4P/sinopia_server/issues/25), [#33  test cognito interactions using sinopia API client](https://github.com/LD4P/sinopia_server/issues/33),
 
## ResourceTemplates and Trellis
- [ ] Writing `resourceTemplates` JSON  to the Sinopia Server's Trellis via API (at least AWS dev or stage) (not done as of 1/24)
  - Linked Data Editor (BFF) Issues
   [#294 JSON schema validation: get schema from url (w version) within resourceTemplate](https://github.com/LD4P/sinopia_editor/issues/294)
  - Sinopia Server Issues
  [#34 tests for storing RDF](https://github.com/LD4P/sinopia_server/issues/34)
- [ ] BFF Write to Trellis (w/ authn/authz via JWT header) (not done as of 1/24)
  - Linked Data Editor (BFF) Issues
   [#281 RDF reducer support in ResourceTemplateModel](https://github.com/LD4P/sinopia_editor/issues/281)
   [#282 ResourceTemplateModal RDF Integration](https://github.com/LD4P/sinopia_editor/issues/282)
   [#283 URI Subjects for ResourceTemplateForm ](https://github.com/LD4P/sinopia_editor/issues/283)
  - Sinopia Server Issues
     [#34 tests for storing RDF](https://github.com/LD4P/sinopia_server/issues/34)
  - [ ] Test first from command-line (not done as of 1/24)

## Sinopia Editor
- [x] React and Redux Overview 
- [x] generating RDF from Editor (was not originally goal in this sprint, but was achieved)

## Stretch Goals
- [ ] Add `schemaVersion` Sinopia Profile Editor metadata field
- [ ] Validate `resourceTemplates`
    - [x] BFF Merged PR [#302 BFF does JSON schema validation of resource template on import](https://github.com/LD4P/sinopia_editor/pull/302) 
    - [ ] Profile editor
    - [ ] Server
- [ ]  BFF Browse and Editor Tab React Stubs
   - [ ] Browse tab has simple search form stub,
   - [ ] Simple search supports QA 
   - [ ] Display Results following UIX design
   - [ ] Implement Editor Forms Styles and layout
