### ISSUE TITLE
Sprint 11

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#156]
##  Cognito support
- [x] Sarav Knowledge Transfer
  - [x] Using Terraform
  - [x] User Interactions/Workflow Form 
        Decided on using all Cognito web forms, host forms on Sinopia.io, or a combination of both approaches. (to be discussed 1/24-1/25)
- [ ] Finish Cognito addition to Terraform for the Sinopia Server 
        Related issues  [#25 Setting up AWS Cognito](https://github.com/LD4P/sinopia_server/issues/25) and  [#33  test cognito interactions using sinopia API client](https://github.com/LD4P/sinopia_server/issues/33)

## Linked Data Editor CI and Tagged Releases
- [x] Setup circle-ci to automatically deploy master branch push requests to https://development.sinopia.io, tracking in ticket [#307 Continous Deployment to Development](https://github.com/LD4P/sinopia_editor/issues/307). User acceptance testing will be done in this
   environment. Complete by PR [#312](https://github.com/LD4P/sinopia_editor/pull/312)
- [ ] Start tagged releases for staging and production
  - [ ] Document process for updating Terraform for BFF to use a specific tag
  - [ ] Release version **0.2.0** following [Semantic Versioning conventions](https://semver.org/). Each minor version should correspond to a Milestone, currently work is on Milestones 2 and 3. April MVP release will be version **1.0.0**.
     
### Starter Set of Templates/Profiles
- [x] prepare JSON schema for templates/profiles meeting Sinopia basic requirements (done, but may need tweaks (LD4P/sinopia#151)
- [x] prepare set of templates/profiles meeting Sinopia basic requirements that schema validate
   - [#10 Sinopia baseline templates](LD4P/sinopia_sample_profiles#10)
   - [#9 use property type lookup, resource, literal with correct support](LD4P/sinopia_sample_profiles#9)

#### Curl calls to Server
- [x] on laptop, using trellis built in user file, curl web acl permissions for user and groups, and curl `resourceTemplate` JSON to local trellis instance via API.
- [ ] [#38 Write `resourceTemplates` JSON  to the Sinopia Server's Trellis via API (at least AWS dev or stage)](https://github.com/LD4P/sinopia_server/issues/38)
    - [ ] requires our AWS instance to have some known users.
  
#### Linked Data Editor (BFF) Issues
   - [ ] [#294 JSON schema validation: get schema from url (w version) within resourceTemplate](https://github.com/LD4P/sinopia_editor/issues/294)
   - [ ] [#309 retrieve resourceTemplate from Trellis within BFF code](https://github.com/LD4P/sinopia_editor/issues/309)
   - [ ] [#310 retrieve resourceTemplate from Trellis by resourceTemplate id (not server id) ](https://github.com/LD4P/sinopia_editor/issues/310)
  
#### Sinopia Server Issues
  - [ ] [#34 tests for storing RDF](https://github.com/LD4P/sinopia_server/issues/34)
  - [ ] [#35 tests for storing templates](https://github.com/LD4P/sinopia_server/issues/35)

### Profile Editor 
- [ ] Begin validating JSON Resource Templates using version **0.1.0** schema.  Tracked in tickets
   - [ ] [#145 JSON validate (resource template) before save](https://github.com/LD4P/sinopia_profile_editor/issues/145)
   - [ ] [#159 include JSON schema url in output template/profile](https://github.com/LD4P/sinopia_profile_editor/issues/159)
   - [ ] [#163 date in resourceTemplate](https://github.com/LD4P/sinopia_profile_editor/issues/163)
   - [ ] [#166 don't display or output defunct attribs](https://github.com/LD4P/sinopia_profile_editor/issues/166)
   - [ ] [#165 only lookup, resource, literal](https://github.com/LD4P/sinopia_profile_editor/issues/165)
   - [ ] [#175 type lookup limits valueConstraints](https://github.com/LD4P/sinopia_profile_editor/issues/175)
   - [ ] [#176 type resource limits valueConstraints](https://github.com/LD4P/sinopia_profile_editor/issues/176)
   - [ ] [#177 type literal limits valueConstraints](https://github.com/LD4P/sinopia_profile_editor/issues/177)
### Elasticsearch
- [ ] [#37 Setup Elasticsearch in Terraform on the Sinopia Server](https://github.com/LD4P/sinopia_server/issues/37)

## Sinopia Linked Data Editor 
- [ ] JSON-LD and RDF 
  - [x] Merge PR [#305 Adds tests, reducer+action, and modal for displaying generated json-ld](https://github.com/LD4P/sinopia_editor/pull/305) closes 
    - [#280 Use N3.Store in RDF Reducer](https://github.com/LD4P/sinopia_editor/issues/280),
    - [#281 RDF reducer support in ResourceTemplateModel](https://github.com/LD4P/sinopia_editor/issues/281)
    - [#282 ResourceTemplateModal RDF Integration](https://github.com/LD4P/sinopia_editor/issues/282)
    - [#289 RDF Visualization Modal](https://github.com/LD4P/sinopia_editor/issues/289)
  - [ ] Call Trellis for minted subject URI, tracking in ticket [#283 URI Subjects for ResourceTemplateForm](https://github.com/LD4P/sinopia_editor/issues/283)

## Sinopia Server
 - [x] Swagger Client Testing [#29 finish writing first pass at integration tests using swagger-codegen client](https://github.com/LD4P/sinopia_server/issues/29)
## Stretch Goals 
- [ ] Create Elasticsearch Index for ResourceTemplates
