### ISSUE TITLE
M01: UAT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#163]
User Acceptance Tests for Milestone 1: Stand-Alone Profile Editor + Sinopia Homepage in UAT in AWS
#### Homepage
- [x] Links to help and resources mocked up including help or feedback button (or link to place to submit request for help) 
#### Profile Editor
*NOTE: all the things in this list have to work in the Profile Editor and correspondingly in the Linked Data Editor, including UI and resulting RDF. The Editor UI and RDF parts come in later milestones*
- [x] Access Profile Editor on web, without authentication
- [x] Create new profile from scratch
- [x] Export profile JSON
- [x] View and edit existing profile from local filesystem, export revised JSON
- [x] Specify default values for lookup and literal fields
- [x] Specify that the object of a property is another Resource Template
- [x] Specify that field value should come from lookup to specified resource  via QA or direct vocabulary lookup (*NOTE Casalini as QA source comes in M02; Sinopia as lookup source comes in M04*)
- [x] Specify that field’s value can come from more than one lookup source
