### ISSUE TITLE
Sprint 12

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#164]
1 Week Sprint

What we hope to accomplish in this Sprint: 
Complete Milestone 2 and store validated 0.1.0+ Resource templates in Trellis using the Sinopia API client.  On-boarding Huda to project.

No discussion of Profiles, at all.

## Finish Milestone 2 Open Issues
- [x] Release version **0.2.0** of apps following [Semantic Versioning conventions](https://semver.org/).
  - [ ] Document process for updating Terraform for BFF to use a specific tag
- [ ] LD4P/sinopia_editor#346 Handle repeatable = true for a modal resource
- [ ] LD4P/sinopia_editor#348 Lookups to multiple sources per field
- [x] LD4P/sinopia_editor#341 Default for InputLiteral being duplicated
- [x] LD4P/sinopia_editor#345 For a form that's a modal, display the value entered or selected on the main ResourceTemplateForm
- [x] LD4P/sinopia_editor#347 indicate when resource is non-repeatable
- [x] LD4P/sinopia_profile_editor#190 indicate all required fields
- [x] LD4P/sinopia_profile_editor#187 # char truncates exported json
- [x] LD4P/sinopia_profile_editor#193 can load v0.1.0 profiles
- [x] LD4P/sinopia_profile_editor#159 include schema in profile and resource templates output for json schema validation
- [x] LD4P/sinopia_profile_editor#166 don't display undesired attributes
- [x] LD4P/sinopia_profile_editor#165 resource templates can only be literal, lookup or resource
- [x] LD4P/sinopia_profile_editor#148 don't allow nested resource templates
- [x] BFF defaults to v0.0.1 schemas when none present (most permissive)
- [x] LD4P/sinopia#161, LD4P/sinopia#170, LD4P/sinopia#174 schemas tweaked per Michelle's instruction:  type resource cannot have defaults;  no description for resource templates
- [x] LD4P/sinopia_sample_profiles#24 remove cruft in sinopia_sample_profiles (confusing old folders and files)
#### Stretch
- [ ] LD4P/sinopia_profile_editor#188 check for all required fields on save
- [ ] LD4P/sinopia_profile_editor#178: don't output empty URIs (as they cause schema validation errors)
- [ ] LD4P/sinopia_profile_editor#163: display date field for resource template
- [ ] profile editor: conditional logic that only allows approp stuff for selected property type (LD4P/sinopia_profile_editor#175, LD4P/sinopia_profile_editor#176, LD4P/sinopia_profile_editor#177, LD4P/sinopia_profile_editor#192)
- [ ] LD4P/sinopia_profile_editor#145 perform JSON validation on save
- [x] LD4P/sinopia_profile_editor#162 it's "author", not "contact"
- [x] LD4P/sinopia_profile_editor#185 fix typo in property template guiding statement label

## Trellis 
- [ ] Use Sinopia API client to add Resource Templates into Trellis
  - [ ] [#38 Write resourceTemplates to AWS Trellis via API](https://github.com/LD4P/sinopia_server/issues/38) 
 - [ ] [#43 Store user WebID extracted from JWT in Trellis ACL](https://github.com/LD4P/sinopia_server/issues/43) 

## Trellis JMS/SNS/SQS Message for Elasticsearch Indexing
- [x] Decide on what mechanism to use for Linked Data Notifications

## Other
- [x] Onboard Huda for Sinopia Editor UIX development

## Stretch
- [ ] Decide if we can/should use S3 for Trellis memento and logging support (https://github.com/LD4P/sinopia_server/issues/50)
- [x] Proof of concept for ECS task (using Fargate) for indexing Resource Template payload (https://github.com/LD4P/sinopia_server/issues/46)
- [x] [#37 Setup Elasticsearch in Terraform for Sinopia Server](https://github.com/LD4P/sinopia_server/issues/37)
- [ ] [#39 server side JSON schema validate incoming resourceTemplates and profiles](https://github.com/LD4P/sinopia_server/issues/39)
- [x]  BFF Browse, Editor, and Import Resource Template Tabs React Stubs [#113](https://github.com/LD4P/sinopia_editor/issues/113) 

### Cognito
- [x] Decision on user creation workflow
- [x] Finish Cognito addition to Terraform for the Sinopia Server 
        Related issues  [#25 Setting up AWS Cognito](https://github.com/LD4P/sinopia_server/issues/25) and  [#33  test cognito interactions using sinopia API client](https://github.com/LD4P/sinopia_server/issues/33)
