### ISSUE TITLE
M03: UAT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#166]
**Milestone 3: User Login and “Profile Opening Night”**

*Users can log in, user can upload profiles to an available profile menu, can upload new versions of own profile; no metadata persisted yet*

**Authentication / Log In**
- [x] User can create/request (actual method depends on what path we choose) new account
- [x] User can retrieve forgotten password or reset password
- [x] Authenticated resources/actions are available after user logs in / authenticated resources/actions are not available if user is not logged in
- [x] User is prompted to log in if trying to access authenticated resources/data/actions without being logged in. Places that need authentication:
  - [x] load a new or updated profile
  - [x] add or change data in a form in the Linked Data Editor. *Note: data is not saved until Milestone 4--the part that's ready in Milestone 3 is the prompt to log in on the Editor Page _(fixing some issues with repeatable fields)_

**User and Group Management**
- [x] ~~admin can create and delete groups and put users in groups and remove users from groups (command line or native whatever is fine)~~ *decided not to do group-based authentication for this work cycle*

**Profile Opening Night**
*Adding and Updating Profiles*
- [x] Authenticated user can upload new profile to a list of "available profiles" that others can then use to catalog (on DEV, inconsistency with new RTs showing up in list of available profiles)
- [x] Profile “owner” can overwrite existing profile with new version of same ~~if they have permission (if no permission, get message to that effect)~~ *not doing group-based authentication in this work cycle, so no special permission required beyond being logged in*
- [x] Profile “owner” trying to overwrite existing profile is asked to confirm overwrite

*Cataloging with Profiles*
- [x] User chooses profile from list of available profiles and opens a form for cataloging using that profile

**Casalini data, postponed from milestone 2**
- [x] Specify Casalini as option for lookup in Profile Editor
- [x] in Editor, search for and select entities/values from Casalini data, as specified in profile

**Comment by michelleif** [comment]
almost done, pending tooltip fix https://github.com/LD4P/sinopia_editor/issues/521

**Comment by michelleif** [comment]
tooltip fix is done
