### ISSUE TITLE
M04: UAT

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#167]
**Milestone 4: Production of Original Data**

*Create and save data in Editor, and find it again (simply) and refer to created entities*

**Creating, previewing and saving RDF**
- [x] Preview RDF before saving
- [x]  RDF produced is correct and complete. (https://github.com/LD4P/sinopia_editor/issues/423). This includes:
     - [x] Diacritics and non-Roman script (incl right-to-left) doesn’t get messed up
     - [x] URIs minted where needed
     - [x] Context nodes handled properly
     - [x] Stuff looked up is returned as proper URI
     - [x] Resource and Property URIs from RT appear correctly
- [x] Save data entered in form to Sinopia system as RDF
- [x] Be prompted to authenticate in order to save data, if not already logged in (currently you are prompted to use any Editor features, see LD4P/sinopia_editor#495 for description of future work)
- [x] Don’t lose your entered data if you hit the browser back button (not sure if this is possible to support)—compare to LC BFE: in LC BFE if you go back and then forward your entered data is still there. This works in Safari at least.
- [x] When saving, be warned if required fields are empty
- [x] Search more than one QA source at a time if specified in Profile.
LD4P/sinopia_editor#348
- [x] when property type=Resource, repeatable = true, be able to open the form multiple times, adding data each time, seeing visual confirmation of each repetition, and and get visual indication when Resource is not repeatable LD4P/sinopia_editor#346
- [x] See default values and be able to change them. 

**Referring**
- [x] In Profile Editor, specify Sinopia ~~(or subset of Sinopia like Works, etc.)~~ as a lookup source
- [x] In Linked Data Editor, lookup and refer to entities in Sinopia as specified by Profile

**Finding**
- [x] Find previously created Sinopia data using simple search (or browse) (see https://github.com/LD4P/sinopia/issues/51 for list of search capability already present in LC BFE), this is on the Browse/Search tab
- [x] View details of  a search result
- [x] Open result in a profile, to edit it, ~~if you have permission to use Editor and to edit that "record"~~ (not doing these permissions in work cycle 1)
- [ ] ~~Be prevented from changing data you don’t have permission to change~~ (Since we postponed the assigning of users to groups, this feature is not yet possible, even though resources are saved to group containers.)
