### ISSUE TITLE
Sprint 13

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#179]
Sprint starts on 25 February 2019 and ends 7 March 2019.

_What we hope to accomplish during this sprint_ - Style Cognito login and sign-up pages so that a valid user sees the **Import Profile** tab; non-authenticated users will get an error message and link to the Cognito login page. Secondly, successfully import all Resource Templates from [0.1.0 Profiles](https://github.com/LD4P/sinopia_sample_profiles/tree/master/profiles/v0.1.0) into Trellis with the corresponding Elasticsearch index using the Sinopia Server's client. 

Assignments:
*  Goal One - @jgreben and @jmartin-sul 
*  Goal Two - @mjgiarlo and @jermnelson 

## General
- [x] Update Sinopia Home page with **0.2.0** release for Milestone 2 [PR #397](https://github.com/LD4P/sinopia_editor/pull/397)

## Cognito
- [x] [#171 AWS Cognito UI Customization](https://github.com/LD4P/sinopia/issues/171)
- [x] [#173 Add new Attributes for Cognito](https://github.com/LD4P/sinopia/issues/173)
- [x] [#372 JWT authorization for import route](https://github.com/LD4P/sinopia_editor/issues/372)

## Sinopia Client and Server
- [x] [#1 Messaging and Indexing Daemon](https://github.com/LD4P/sinopia_indexing_pipeline/issues/1)
- [ ] [#42 figure out ACL update strategy (from JS SDK side)](https://github.com/LD4P/sinopia_server/issues/42)
- [x] [#38 Write resourceTemplates to AWS Trellis via API](https://github.com/LD4P/sinopia_server/issues/38)

## Stretch Goals
- [x] [#2 Ensure pipeline deals properly with deletes](https://github.com/LD4P/sinopia_indexing_pipeline/issues/2)
- [ ] [#373 Upload Profile to Sinopia Server](https://github.com/LD4P/sinopia_editor/issues/373)
- [x] [#62 Create a node.js module for npm](https://github.com/LD4P/sinopia_server/issues/62)
