### ISSUE TITLE
Sprint 14

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#184]
Sprint starts on 7 March 2019 and ends 21 March 2019.

_What we hope to accomplish during this sprint_: Successful import Resource Templates contained in profiles through the Linked Data **Import Resource Templates** tab, saved to Trellis, indexed into Elasticsearch, and loading the UI in the **Editor** tab.

## Linked Data Editor
- [ ] New UI Implementation
  - ~LD4P/sinopia_editor#377 - PR UI Implementation and Redux Store Changes~
  - LD4P/sinopia_editor#387 - PropertyOutline Rendering of Resource Template (Monday, 3/18)
  - LD4P/sinopia_editor#412 - InputLiteral, InputListLOC, and InputLookupQA use common reducers (Tuesday, 3/19)
  - LD4P/sinopia_editor#411 - Defaults from Resource Templates Rendering (Weds. 3/20)
  - LD4P/sinopia_editor#387 - PropertyPanel UI -- Add Button disabled when repeatable is false and more than one value (Friday 3/22) **lower priority**
- [x] Import Resource Template Tab - PR LD4P/sinopia_editor#408
  -  [#394 When a profile or resource template is loaded via the Import Resource Tab update the Editor tab](https://github.com/LD4P/sinopia_editor/issues/394)
- [ ] Refactor Sinopia Server Spoof call to use Elasticsearch query for Resource Templates
  - [#309 retrieve resourceTemplate from server](https://github.com/LD4P/sinopia_editor/issues/309) (Thursday, 3/21)
- [ ] Interactions and UI of Resource Templates
  - LD4P/sinopia_editor#373 - Upload Profile to Sinopia Server (Weds. 3/20)
  - LD4P/sinopia_editor#418 - Display a List of Available Resource Templates (Friday, 3/22)
- [x] Create a tagged version `0.2.1` to reflect Sprint 13 work.

## Sinopia Server
- [x] send JWT and get (authenticated/authorized) responses for specific resource templates in the **ld4p** group
  - ~LD4P/sinopia_server#71 - pass JWT to trellis~
  - LD4P/sinopia_server#70 - configure trellis properly for JWT decoding (Friday, 3/15)
- [ ] ACL support in Trellis - adding "bare-bones" support for adding a user to the **ld4p** group need for saving a ResourceTemplate to Trellis.
   - ~[#1 work with a local server for development and for testing](https://github.com/LD4P/sinopia_acl/issues/1)~
   - ~[#2 get WebACL for group from server](https://github.com/LD4P/sinopia_acl/issues/2)~ (Weds 3/20)
   - ~[#3 given a retrieved webACL file, add a webid to it](https://github.com/LD4P/sinopia_acl/issues/3)~ (Monday, 3/18)
   - [#5 use JWT from .ENV file for WebACL update permissions](https://github.com/LD4P/sinopia_acl/issues/5) (Thursday, 3/21)
