### ISSUE TITLE
Sprint 15

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#187]
Sprint starts on 21 March 2019 and ends 4 April 2019 (with 3 day LDCX break).

_What we hope to accomplish during this sprint_: Complete Milestone 3, begin support for generating RDF from a loaded Resource Template form in the editor.

## Milestone 3 
- [ ] Linked Data Editor - UI Changes
   - [ ] LD4P/sinopia_editor#412 - ~~InputLiteral~~ [PR#426](LD4P/sinopia_editor#426), InputListLOC, and InputLookupQA use common reducers (Tuesday, 3/27)
      - LD4P/sinopia_editor#429 -  InputLookupQA uses selectorReducer
      - LD4P/sinopia_editor#430 - InputListLOC uses selectorReducer  
  - ~~LD4P/sinopia_editor#422 - Add Casalini QA Sources~~ [PR#425](LD4P/sinopia_editor#425)
  - LD4P/sinopia_editor#309 - load to and retrieve resourceTemplates from trellis server
  - LD4P/sinopia_editor#418 - Display a List of Available Resource Templates (Friday, 3/22)
  - ~~LD4p/sinopia_editor#348 - lookups to multiple sources per field~~
  - LD4P/sinopia_editor#393 - Display resourceLabel and resourceId in Editor Header
- [ ] Sinopia Server
  - LD4P/sinopia_server#27 - Store and Mint URIs for resourceTemplates
  - LD4P/sinopia_server#89 - JWT refreshing
  - LD4P/sinopia#192  - provision local VM for ACL management
- [ ] Sinopia Server ACL
   - [ ] LD4P/sinopia_acl#32 - CLI for adding users to groups, etc.
   - [ ] LD4P/sinopia_acl#33 - Http plumbing w cognito
   - [ ] LD4P/sinopia_acl#30 - Server migration script with root, repo containers and right WebACL
   - [ ] LD4P/sinopia_acl#29 - user emails -> webids

 
### Starting RDF Support
- [ ] Linked Data Editor
  - LD4P/sinopia_editor#134 - ResourceTemplate form: add submit and cancel buttons
  - LD4P/sinopia_editor#283 - URI Subjects for ResourceTemplateForm
  - LD4P/sinopia_editor#321 - Dynamically generate proper RDF of repeatable literals
  - LD4P/sinopia_editor#313 - Prompt user to save RDF
  - LD4P/sinopia_editor#404 - Preview RDF Modal Working Again
  - LD4P/sinopia_editor#323 - Make the escape key work in order to close rdf modal

###  Sinopia Server
- [ ] Indexing Pipeline
  - LD4P/sinopia_indexing_pipeline#15 - Index RDF into a separate ES Index
  - LD4P/sinopia_server#45 - Reindex Trellis into Elasticsearch
- [ ] Trellis
  - LD4P/sinopia_editor#283 - URI Subjects for ResourceTemplateForm
  - LD4P/sinopia_server#34 - tests for storing RDF
