### ISSUE TITLE
Sprint 16

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#188]
Sprint starts on 4 April 2019 and ends 25 April 2019.

_What we hope to accomplish during this sprint_: User acceptance testing completed on Milestone 3. User opens an existing Resource Template in the editor, creates a RDF graph from a mixture of InputLiterals, InputList, InputLookup, and embedded Resource Templates.

### Sinopia Editor
- [ ] Linked Data Editor - UI Changes
  - [x] LD4P/sinopia_editor#441 - PR Embedded resource template Redux support for UI 
  - [ ] LD4P/sinopia_editor#429 -  InputLookupQA uses selectorReducer
  - [ ] LD4P/sinopia_editor#430 - InputListLOC uses selectorReducer
  - [x] LD4P/sinopia_editor#393 - Display resourceLabel and resourceId in Editor Header
  - [x] LD4P/sinopia_editor#309 - load to and retrieve resourceTemplates from trellis server
  - [x] LD4P/sinopia_editor#418 - Display a List of Available Resource Templates

### Sinopia Server
  - [ ] LD4P/sinopia_server#27 - Store and Mint URIs for resourceTemplates (intregation w editor)
  - [ ] LD4P/sinopia_server#89 - JWT refreshing
  - [ ] ~~LD4P/sinopia#192  - provision local VM for ACL management~~

### SInopia Stack Learning
- [x] LD4P/sinopia#197 React Tutorial
- [x] LD4P/sinopia#198 Redux Tutorial

### Waffle board migration to Sinopia Github Project
- [x] Migrate waffle board to use Sinopia Github Project
### Sinopia Server ACL
   - [ ] ~~LD4P/sinopia_acl#32 - CLI for adding users to groups, etc.~~
   - [x] LD4P/sinopia_acl#33 - Http plumbing w cognito
   - [x] LD4P/sinopia_acl#30 - Server migration script with root, repo containers and right WebACL
   - [x] LD4P/sinopia_acl#29 - user emails -> webids

## Starting RDF Support
- [ ] Linked Data Editor
  - [ ] LD4P/sinopia_editor#134 - ResourceTemplate form: add submit and cancel buttons
  - [ ] LD4P/sinopia_editor#283 - URI Subjects for ResourceTemplateForm
  - [ ] LD4P/sinopia_editor#321 - Dynamically generate proper RDF of repeatable literals
  - [ ] LD4P/sinopia_editor#313 - Prompt user to save RDF
  - [ ] LD4P/sinopia_editor#404 - Preview RDF Modal Working Again
  - [ ] LD4P/sinopia_editor#323 - Make the escape key work in order to close rdf modal

**Comment by ndushay** [comment]
@jermnelson I am closing this Sprint 16 ticket;  if that's incorrect, please re-open.
