### ISSUE TITLE
Sprint 17

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#189]
Sprint starts on 25 April 2019 and ends 9 May 2019

_What we hope to accomplish during this sprint_:  Finish UAT testing for Milestone 3, deploying to sinopia.io for use by the cohort. 

#### Project board stats at outset (Thurs Apr 25, 3:30pm) 
- Backlog - 3/75 (M3/total)
- Ready - 10/21
- In Progress - 14/17
- Done - 34/144

## MIlestone 3
- [ ] LD4P/sinopia#202 - Create Tagged Release 0.2.5

### Linked Data Editor
- [ ] LD4P/sinopia_editor#464 - Profile gets error upon import to Linked Data Editor
- [ ] LD4P/sinopia_editor#460 - Manage sessions using amplify sdk
- [ ] LD4P/sinopia_editor#455 - Resource Template reducers causing inconsistent Redux state
- [ ] LD4P/sinopia_editor#429 -  InputLookupQA uses selectorReducer
- [ ] LD4P/sinopia_editor#430 - InputListLOC uses selectorReducer

### Sinopia Server
- [ ] LD4P/sinopia_acl#65 - ENV vars and ??? in AWS setup for sinopia_acl 
- [ ] deploy sinopia_acl (in trellis container) to AWS 
- [ ] LD4P/sinopia_acl#58 - populateEmptyTrellis script works on aws DEVELOPMENT
- [ ] LD4P/sinopia_acl#59 - populateEmptyTrellis script works on aws STAGE 
- [ ] LD4P/sinopia_acl#60 - populateEmptyTrellis script works on aws PRODUCTION

## Milestone 4
