### ISSUE TITLE
Create container structure & ACLs as part of server migration

### ISSUE THREAD

**Issue by mjgiarlo** [LD4P/sinopia#196]
# Description / Rationale

The goal of this work is to ensure that whenever we spin up the Sinopia server (based on Trellis's trellis-ext-db product), it is available with the required containers and ACLs without any manual intervention required. We should make sure this is working in multiple contexts:

* when doing development of `sinopia_editor`
* when doing development of `sinopia_server`
* when doing development of `sinopia_acl`
* when deploying to development and production in AWS

# Required work

- [x] Merge LD4P/sinopia_acl#50
- [x] Clarify our current groups/ACLs approach is sufficient for MVP (today @ 2pm)
  * Confirmed ACL approach is sufficient. Need to add groups to migration script. @michelleif will provide that list of groups (and, ideally, an rdfs:label for each one). Can you paste that info in a comment to this issue? (Unless there's a better place for it, in which case you can point me at that instead. I'm flexible.)
- [x] Add a bunch of groups to the server migration work (see :point_up:)
- [x] Wrap ACL migration functionality (currently in an npm script) in a `bin/migrate` so that importing codebases can invoke what was added in LD4P/sinopia_acl#50 -- LD4P/sinopia_acl#51
- [x] Replace `PUT` calls in sinopia_acl's `src/populateEmptyTrellis.js` with `PATCH` calls to make the migration safe to call multiple times without wiping out data -- LD4P/sinopia_acl#51
- [x] Integrate :point_up: functionality in sinopia_acl's `docker-compose` configuration so that when Trellis spins up, `bin/migrate runs` -- LD4P/sinopia_acl#52
- [x] Bump version and publish `sinopia_acl` as an NPM package -- https://github.com/LD4P/sinopia_acl/pull/53
- [x] Dockerize `sinopia_acl` for easier inclusion into editor and server -- https://github.com/LD4P/sinopia_acl/pull/54
- [x] Add `platformdata` services in the `docker-compose` config of `sinopia_editor` so `bin/migrate` from `sinopia_acl` runs automatically when spinning up Trellis -- https://github.com/LD4P/sinopia_server/pull/93
- [x] Add `platformdata` services in the `docker-compose` config of `server` so `bin/migrate` from `sinopia_acl` runs automatically when spinning up Trellis -- https://github.com/LD4P/sinopia_editor/pull/449
- [x] Do ... something to make this happen in our AWS buildout for both dev and prod (@rsmith11 will do this in Terraform)

**Comment by michelleif** [comment]
Container names. Label in quotes. slug following (I'm not sure what a slug is so if it's something different you want lmk)

"University of Alberta" | alberta
"University of Colorado, Boulder" | boulder
"University of Chicago" | chicago
"Cornell University" | cornell
"Library of Congress" | dlc
"Duke University" | duke
"Frick Art Reference Library" | frick
"Harvard University" | harvard
"University of Texas, Austin, Harry Ransom Center" | hrc
"University of Michigan" | michigan
"University of Minnesota" | minnesota
"National Library of Medicine" | nlm
"Northwestern University" | northwestern
"PCC" | pcc
"University of Pennsylvania" | penn
"Princeton University" | princeton
"Stanford" | stanford
"Texas A&M University" | tamu
"University of California, Davis" | ucdavis
"University of California, San Diego" | ucsd
"University of Washington" | washington
"Yale University" | yale

**Comment by mjgiarlo** [comment]
@michelleif rad! thanks, that's perfect. I'll get on this momentarily.

**Comment by mjgiarlo** [comment]
My bits of this ticket are now done and I'm handing it off to @rsmith11. Lmk if I can do anything to help.

**Comment by rsmith11** [comment]
Does the sinopia_acl container need a public-facing IP/URL?

**Comment by mjgiarlo** [comment]
@rsmith11 Nope.

**Comment by rsmith11** [comment]
I attempted to run the container in STAGE but the container appeared to do nothing.  I believe I have the right ENV variables being passed to it, but could it be the same situation with the sinopia_server that the ENVs aren't being passed?

**Comment by mjgiarlo** [comment]
@rsmith11 Which container did you run in stage? Would it be helpful to pair on this, even for a few minutes (since we are both in the office)?

**Comment by mjgiarlo** [comment]
> I attempted to run the container in STAGE but the container appeared to do nothing. I believe I have the right ENV variables being passed to it, but could it be the same situation with the sinopia_server that the ENVs aren't being passed?

No output?

**Comment by rsmith11** [comment]
Progress after adding command: ```retrieving Cognito token
creating root container
creating repository container
creating alberta group container
creating boulder group container
creating chicago group container
creating cornell group container
creating dlc group container
creating duke group container
creating frick group container
creating harvard group container
creating hrc group container
creating ld4p group container
creating michigan group container
creating minnesota group container
creating nlm group container
creating northwestern group container
creating pcc group container
creating penn group container
creating princeton group container
creating stanford group container
creating tamu group container
creating ucdavis group container
creating ucsd group container
creating washington group container
creating yale group container
setting root container ACLs
ERROR: problem getting cognito accessToken: { code: 'UserNotFoundException',
name: 'UserNotFoundException',
message: 'User does not exist.' }
ERROR: problem getting webid for jpnelson: { UserNotFoundException: User does not exist.
at Request.extractError (/home/circleci/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/home/circleci/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/home/circleci/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /home/circleci/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'User does not exist.',
code: 'UserNotFoundException',
time: 2019-05-07T22:30:00.909Z,
requestId: 'a6d38fe6-7117-11e9-a967-fdef37112cc8',
statusCode: 400,
retryable: false,
retryDelay: 66.95985618293254 }
(node:18) UnhandledPromiseRejectionWarning: ERROR: problem getting webid for jpnelson: { UserNotFoundException: User does not exist.
at Request.extractError (/home/circleci/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/home/circleci/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/home/circleci/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /home/circleci/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'User does not exist.',
code: 'UserNotFoundException',
time: 2019-05-07T22:30:00.909Z,
requestId: 'a6d38fe6-7117-11e9-a967-fdef37112cc8',
statusCode: 400,
retryable: false,
retryDelay: 66.95985618293254 }
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
ERROR: problem getting webid for michelle: { UserNotFoundException: User does not exist.
at Request.extractError (/home/circleci/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/home/circleci/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/home/circleci/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /home/circleci/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'User does not exist.',
code: 'UserNotFoundException',
time: 2019-05-07T22:30:00.916Z,
requestId: 'a6d3b744-7117-11e9-9e45-3124fcf1d7c6',
statusCode: 400,
retryable: false,
retryDelay: 58.6143406700957 }
ERROR: problem getting webid for mjgiarlo: { UserNotFoundException: User does not exist.
at Request.extractError (/home/circleci/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/home/circleci/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/home/circleci/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /home/circleci/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'User does not exist.',
code: 'UserNotFoundException',
time: 2019-05-07T22:30:00.917Z,
requestId: 'a6d36922-7117-11e9-9e45-3124fcf1d7c6',
statusCode: 400,
retryable: false,
retryDelay: 13.020565663886297 }
ERROR: problem getting webid for jgreben: { UserNotFoundException: User does not exist.
at Request.extractError (/home/circleci/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/home/circleci/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/home/circleci/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /home/circleci/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'User does not exist.',
code: 'UserNotFoundException',
time: 2019-05-07T22:30:00.923Z,
requestId: 'a6d38fa4-7117-11e9-9034-ddfc9a2d6441',
statusCode: 400,
retryable: false,
retryDelay: 33.212974983372035 }
ERROR: problem getting webid for suntzu: { UserNotFoundException: User does not exist.
at Request.extractError (/home/circleci/node_modules/aws-sdk/lib/protocol/json.js:51:27)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
at Request.emit (/home/circleci/node_modules/aws-sdk/lib/request.js:683:14)
at Request.transition (/home/circleci/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/home/circleci/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /home/circleci/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/home/circleci/node_modules/aws-sdk/lib/request.js:685:12)
at Request.callListeners (/home/circleci/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
message: 'User does not exist.',
code: 'UserNotFoundException',
time: 2019-05-07T22:30:00.924Z,
requestId: 'a6d4a142-7117-11e9-9b7c-6f33a367d0e8',
statusCode: 400,
retryable: false,
retryDelay: 95.85846415410329 }```

**Comment by rsmith11** [comment]
This is in the stage environment, so there are no Cognito users except the `sinopia-devs_client-tester` user

**Comment by mjgiarlo** [comment]
@rsmith11 That looks like promising progress! Anything we can do to help w/ this? cc: @jermnelson

**Comment by rsmith11** [comment]
Here's the Cloudwatch logs from DEV when running the acl container ```retrieving Cognito token
creating root container
creating repository container
creating alberta group container
creating boulder group container
creating chicago group container
creating cornell group container
creating dlc group container
creating duke group container
creating frick group container
creating harvard group container
creating hrc group container
creating ld4p group container
creating michigan group container
creating minnesota group container
creating nlm group container
creating northwestern group container
creating pcc group container
creating penn group container
creating princeton group container
creating stanford group container
creating tamu group container
creating ucdavis group container
creating ucsd group container
creating washington group container
creating yale group container
setting root container ACLs
ERROR: problem getting cognito accessToken: { code: 'UserNotFoundException',
name: 'UserNotFoundException',
message: 'User does not exist.' }```

**Comment by mjgiarlo** [comment]
@rsmith11 This seems like it is a problem with the Cognito admin user. Looking over https://us-west-2.console.aws.amazon.com/ecs/home?region=us-west-2#/taskDefinitions/sinopia-acl/6, I see a typo in the value of `COGNITO_ADMIN_USER`. It's set to `sinopia-dev_client_tester` but I think it needs to be `sinopia-devs_client-tester`. Give that a shot?

**Comment by rsmith11** [comment]
Sorry for the typo.  I updated it in DEV (which has all users) and it ran without errors.  Submitted Terraform PR to merge in all Envs.

**Comment by mjgiarlo** [comment]
@rsmith11 Np! Glad to hear it's working.

**Comment by rsmith11** [comment]
acl container in place in all environments, and cloudwatch event setup to run every Sunday.

**Comment by mjgiarlo** [comment]
@rsmith11 Awesome! Now that all the boxes are ticked, I think we can close the issue. What do you say?

cc: @jermnelson
