### ISSUE TITLE
Work Cycle One

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#199]
# Work-Cycle One
## Feature Punch-List
The MVP provides a collaborative Linked Data Editing environment and allows LD4P2 Cohort institutions to start cataloging their collections.

### Total Completed Issues:  75% 85/112
- [ ] Sinopia [M3](https://github.com/LD4P/sinopia/milestone/9) 11/13
- [ ] Editor [M3](https://github.com/LD4P/sinopia_editor/milestone/6) 28/44
- [ ] Server [M3](https://github.com/LD4P/sinopia_server/milestone/2) 23/25
- [x] Indexing Pipeline [M3](https://github.com/LD4P/sinopia_indexing_pipeline/milestone/1) 1/1
- [ ] ACL [M3](https://github.com/LD4P/sinopia_acl/milestone/1) 21/26
- [x] UserBackup [M3](https://github.com/LD4P/sinopia_user_backup/milestone/1) 2/2
- [ ] UAT [M3](https://github.com/LD4P/sinopia/issues/166) 7/13 (not included in percentage)

### Total Completed Issues:  30% 18/59
- [ ] Sinopia [M4](https://github.com/LD4P/sinopia/milestone/10) 5/12
- [ ] Editor [M4](https://github.com/LD4P/sinopia_editor/milestone/4) 11/36
- [ ] Server [M4](https://github.com/LD4P/sinopia_server/milestone/3) 0/7
- [ ] Indexing Pipeline [M3](https://github.com/LD4P/sinopia_indexing_pipeline/milestone/2) 0/2
- [ ] UserBackup [M4](https://github.com/LD4P/sinopia_user_backup/milestone/2) 0/2
- [ ] UAT [M4](https://github.com/LD4P/sinopia/issues/167) 1/20 (not included in percentage)

**Comment by michelleif** [comment]
work cycle 1 is over!
