### ISSUE TITLE
Sprint 20

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#223]
**What we hope to accomplish this sprint** Finish Milestone 3. Start RDF generation based on the Redux state of the Linked Data application, displaying results in the Preview RDF modal. 

- [ ] RDF Graph generated and validated
- [ ] From Redux State and displayed in Preview RDF
- [ ] RDF Graph contains the provenance info to retrieve Memento URI of Resource Template 
- [x] Preview RDF Save Button displays dialog for selecting group to save RDF - done 
- [ ] Select Group dialog uses Sinopia Client to send RDF Payload to Trellis by calling API
