### ISSUE TITLE
Sprint 21

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#226]
## June 6th-June 20th 
**What we hope to accomplish this sprint** Save and publishing the RDF; retrieve RDF from server (with direct URI):

- [x] RDF Graph generated and validated
- [x] From Redux State and displayed in Preview RDF
-  ~~RDF Graph contains the provenance info to retrieve Memento URI of Resource Template~~ Trellis provided auditing and provenance provides this for containers
- [x] Select Group dialog uses Sinopia Client to send RDF Payload to Trellis by calling API
- [x] Server - RDF Graph is saved in Trellis, mints an entity URI within the group container
- [x] Entity URI is returned and saved to the Redux State (to persist the URI and user can continue to edit) 
-  ~~Entity URI route for returning RDF (publish dereferenceable URI)~~ @michelleif determined that Trellis URI is sufficient. 
- [x] Integration testing for RDF graphs generated from different Resource Templates
- [x] Bug fixes

### Stretch 
- [ ] Existing RDF graph transformed into Redux based on Retrieved Resource Template(s)
 

from [Sinopia Milestone 4 Task List](https://docs.google.com/document/d/1nO6IEuDPNSvIsjf7cnnCpAmLRXi_QOUV6m42cDiSax4/edit#heading=h.6l2ua693y736)
