### ISSUE TITLE
Sprint 22

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#230]
# June 20th to July 3rd.

- [ ] Existing RDF graph transformed into Redux based on Retrieved Resource Template(s) - In progress
- [x] Title (and maybe other fields per analysis) indexed into Elasticsearch  
- [ ] Express route for search wrapping Elasticsearch queries from Editor Open 
- [x] Integration testing for RDF graphs generated from different Resource Templates
- [x] Bug fixes

## Stretch
- [ ] Add Sinopia sources to Configuration list of authorities in Profile Editor
- [ ] InputLookupSinopia React Component created (be able to reference already created Sinopia entity)

From  [Sinopia Milestone 4 Task List](https://docs.google.com/document/d/1nO6IEuDPNSvIsjf7cnnCpAmLRXi_QOUV6m42cDiSax4/edit#heading=h.6l2ua693y736)
