### ISSUE TITLE
Sprint 23

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#232]
# July 3rd to July 18th
- [x] Existing RDF graph transformed into Redux based on Retrieved Resource Template(s) 
- [x] Refactor Redux-React components 
- [x] Express route for search wrapping Elasticsearch queries from Editor Open
- [x] InputLookupSinopia React Component 
- [x] Bug Fixes and Refactoring
- [x] Test improvement

# Remaining Milestone 4 Tasks

- [x] Simple Search React Component in the Search tab
- [x] Display Search Results of RDF entities in a table with paging of results in Search tab - in progress
- [x] Clickable link for an entity first retrieves latest version of RDF from Trellis
- [ ] Editing Entity values in Linked Data Editor can be saved back into Trellis, should not display Select Group dialog
- [ ] Edited changes in RDF, saved back to Trellis, is reindexed into Elasticsearch 

From  [Sinopia Milestone 4 Task List](https://docs.google.com/document/d/1nO6IEuDPNSvIsjf7cnnCpAmLRXi_QOUV6m42cDiSax4/edit#heading=h.6l2ua693y736)
