### ISSUE TITLE
Sprint 24

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia#234]
# July 18th through August 7th
## Finish Milestone 4 - All remaining tasks
- [x] User Acceptance Testing for M4
- [x] Editing Entity values in Linked Data Editor can be saved back into Trellis, should not display Select Group dialog
- [x] Add/expand buttons UI changes and implementing
- [x] Edited changes in RDF, saved back to Trellis, is reindexed into Elasticsearch 
- [x] Bug Fixes and Refactoring
- [x] Test improvement 

From  [Sinopia Milestone 4 Task List](https://docs.google.com/document/d/1nO6IEuDPNSvIsjf7cnnCpAmLRXi_QOUV6m42cDiSax4/edit#heading=h.6l2ua693y736)
