### ISSUE TITLE
SC #1: Create original bibliographic metadata for library materials in the domains and formats supported by a limited set of PCC-approved profiles, roughly equivalent to LC’s current set of profiles

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#88]
child tickets in user priority order:
- re #79: CR*D for resources RDF _only the create part is relevant, and that's done_
- [x] parent of LD4P/sinopia_editor#303: required fields enforced
- [x] parent of #46: diacritics
- [x] parent of #74: non-Latin characters
- re #62: validation at field-level _we're not doing this but we do validate the entire form_
- re #65: entity creation locally _we're not doing this in WC1_
- [x] parent of #28: default values set by Profile creator are properly displayed
- re #43: save metadata as draft _not doing this because we have preview RDF_
- [x] parent of #24: resulting RDF correctly reflects properties specified by Profile
- [x] parent of #25: field "types" reflected correctly in Editor
- [x] parent of #75: store the RDF data
- [x] parent of #47: keyboard-based nav
- re #73: notify user if data changes during session _we're not doing this in WC1_
- re #81: meaningful error messages _this was a general statement, nothing specific_
