### ISSUE TITLE
SC #6: Create, use, and share new profiles, including using existing profiles as a starting point, with the ability to specify external lookups from a limited set of possibilities

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#89]
Child tickets organized by user priority:

HIGH PRIORITY
- [x] parent of #21: end-users can create forms
- [x] parent of #42: works with existing forms
- [x] parent of #22: use any ontology or vocab
- [x] parent of #36: help text
- [x] parent of #40: edit existing forms
- [x] parent of #35: copy existing form to create a new form
- [x] parent of LD4P/sinopia_profile_editor#4: "save" button exports JSON
- [x] parent of #9: basic metadata on profiles
- [x] parent of LD4P/sinopia_profile_editor#39: "create profile" page
- [x] parent of LD4P/sinopia_profile_editor#38: profile editor "home page"
- [x] parent of #27: obligation
- [x] parent of #32: context nodes
- [x] parent of #38: multi-entity forms
- re #30: value lists _not doing this in WC1_
- [x] parent of #28: default values
- [x] parent of #23: default resources as subject of form
- [x] parent of LD4P/sinopia_profile_editor#10: profile author required
- [x] parent of #10: upload profiles
- [x] parent of #24: map fields to predicates
- [x] parent of #33: reorder fields and groups of fields
- [x] parent of LD4P/sinopia_profile_editor#26: design profile editor

MEDIUM PRIORITY
- [x] parent of #29: limit values to subset of vocab values _note this is supported by QA subauthorities_
- [x] parent of #25: map form values to input types
- [x] parent of LD4P/sinopia_profile_editor#2, branding
- [x] parent of LD4P/sinopia_profile_editor#3: remove edit/delete button
- [x] parent of LD4P/sinopia_profile_editor#8: adherence optional

LOW PRIORITY
- [x] parent of LD4P/sinopia_profile_editor#37: branding header/footer
- [x] parent of #37: group related fields into sections
- [x] parent of #31: filter external lookup (like #29, this is handled w QA subauthorities)
- [x] parent of LD4P/sinopia_profile_editor#9: profile source as optional field

**Comment by cmh2166** [comment]
See #9 for first steps / questions.
