### ISSUE TITLE
SC #3 part 2: Search and view data created in Sinopia (advanced search)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#90]
Release 1.0 includes basic search (search title properties, see results, open a result in Editor); Work Cycle 2 to address advanced search features, in order by priority:
- [x] allow search by Sinopia URI (parent of ld4p/sinopia_editor#1321) _we only index things with titles, so this currently only applies to things with titles_
- [x] display additional data for each search result: (parent of ld4p/sinopia_editor#1412)
    - class of resource
    - group where resource is stored (i.e., institution that created it)
    - date created (QUESTION: and date modified, separately?)
- [x] allow sorting of results by: (parent of ld4p/sinopia_editor#1519)
    - class of resource
    - group where resource is stored (i.e., institution that created it)
    - date created (QUESTION: and date modified, separately?)
- [x] add descriptive text to UI to explain how the searching works (wildcards? typeahead? what fields are being searched?) (parent of ld4p/sinopia_editor#1259)
- [x] include RDA title properties in what is considered a Title (parent of LD4P/sinopia_indexing_pipeline#1637)
- [x] index all literals in resource (parent of LD4P/sinopia_indexing_pipeline#65)
- [x] index all resources (parent of LD4P/sinopia_indexing_pipeline#89)
- [x] store and index labels when user selects a value from a lookup, so that the value can be searched on later (parent of ld4p/sinopia_editor#1641)
- [ ] allow filtering/faceting of results after a basic search, by the following facets: (parent of ld4p/sinopia_editor#1696; design in Astrid's images below)
    - class of resource
    - group where resource is stored (i.e., institution that created it)
    - date created (QUESTION: and date modified, separately?) (decided not to add Date facet for now)
------
Lower priority below
-------
- add advanced search option to Search tab (default option is basic search) (parent of https://github.com/LD4P/sinopia_editor/issues/1299)
    - specify which field you're searching
    - limit results in advance to a particular facet. (parent of ld4p/sinopia_editor#1153)
- browse recently created resources (so you can just look at the most recent things without having to do a search)--effectively the same as searching for * and then sorting by creation date, most recent first, so not ticketing this

NOTE:
*copying* (aka  deriving from) a search result is covered separately in https://github.com/LD4P/sinopia/issues/95

ADDITIONAL FEATURES BEING WORKED ON AS TIME PERMITS AND USERS DEMAND:
- other fields besides Title that are privileged in search result relevance 
- type-ahead. see https://github.com/LD4P/sinopia_editor/issues/1166

**Comment by michelleif** [comment]
parent of #58

**Comment by michelleif** [comment]
also see 
https://github.com/LD4P/sinopia_editor/issues/1121 and https://github.com/LD4P/sinopia_editor/issues/1120

**Comment by michelleif** [comment]
results design from astrid (copied from #255)
[image](https://user-images.githubusercontent.com/42216982/66066286-17955700-e4fe-11e9-8e56-07588ea2098e.png)

**Comment by michelleif** [comment]
Design from Astrid showing sorting

![66604889-e05d2080-eb63-11e9-8eaa-c53e747cc6b1](https://user-images.githubusercontent.com/23069165/67067549-95c34180-f12b-11e9-8e40-1779d3def5de.png)


The 'Sort by' drop down allows user to sort by title, date, relevance.
There is a secondary selection user makes when they pick 'Sort by'.
a. For title: Ascending, descending
b. For date: Oldest on top, newest on top
c. For Relevance: Most relevant, least relevant (or you can skip this one if you think everyone will just pick most relevant)
