### ISSUE TITLE
SC #5: Link to existing entities created in Sinopia and from a limited set of external sources, including Casalini Share-VDE entities

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#92]
child tickets in order of user priority:
- [x] parent of #58: work lookups for linking/referencing
- [x] parent of #53: lookups to external vocabs
- [x] parent of #12: QA lookups
- [x] parent of #56: context for lookups
- [x] parent of #55: lookups based on different external entity points
- [x] parent of #60: add label when selecting URI
- re #57: restrict search to selected entity stores _not doing this in WC1_
