### ISSUE TITLE
SC #8: Export data from Sinopia

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#94]
Users want to export resource descriptions from Sinopia. Example uses: experiment with linked data discovery using data created in Sinopia; figure out workflows for Sinopia data to get back into ILS; use data in another linked data cataloging system for comparison...

In priority order:
- [x] export all resource descriptions (parent of #253)
- [x] export resource descriptions for a given group (parent of #254)
- [x] include Trellis URI in export (parent of LD4P/sinopia_exporter#53)

Ok if we don't get to:
- export a single description from Editor view (this is already technically possible by doing a preview and copying the data there; this would be a single-click way to do this more easily)
- export single description from Search (you can do this already by opening the description in the Editor then previewing / copying)
- export a found set from Search tab; in original Sinopia plan we said that "filtering of data for export" is out of scope.

EXISTING WORK from Work Cycle 1
https://github.com/LD4P/sinopia_exporter/

EXPORT FORMAT
* what format do we want the export in? what format would be easiest to use? N-triples?

PUSH INSTEAD OF PULL
* export of all resources and export of a group's resources could also be satisfied by us posting a downloadable file periodically, which anyone could then use

OUT OF SCOPE
* offering a choice of more than one export format, given that there are tools that can convert from one format to another
* ability to select individual items from a Search result set and export only those descriptions

QUESTION from below comment
Should we be exporting cached labels as well as resource uris? Answer: Do we cache labels?

**Comment by michelleif** [comment]
@astridu can you reference your Export designs here?

**Comment by astridu** [comment]
Some options. Let me know if these are feasible.

1. Download from record view. 
![image](https://user-images.githubusercontent.com/42216982/64575440-c3e18480-d328-11e9-9db7-8e5e5efea9ce.png)

2. Download from search results view. Users expressed a desire to pick and choose. I placed checkboxes next to the results. User can then select which they want to download (all, one, none, or some selection of the results), and then click the download link.
![image](https://user-images.githubusercontent.com/42216982/64575489-f5f2e680-d328-11e9-826d-148bf58af70e.png)

**Comment by michelleif** [comment]
cool. there should also be a way to just "export everything from x container", without having to search, then select all

**Comment by justinlittman** [comment]
Can you clarify what you mean by "x container"?

Also, can you clarify how selecting is supposed to work with results paging?

**Comment by michelleif** [comment]
just meant that users should be able to say:
export all descriptions that were saved to the [x] group, x being Stanford, Alberta, PCC, etc.

are you asking, what if you want to select things on more than one page for export?

**Comment by michelleif** [comment]
this is done except for the work to automatically generate each week and replace old with new

**Comment by justinlittman** [comment]
Actually, that is done already.

**Comment by michelleif** [comment]
woot. i saw that those issues were open
