### ISSUE TITLE
SC #7: Copy Casalini Share-VDE data (or Discogs) to start a new resource (aka Derive)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia#95]
The purpose of copying data from Share-VDE (which is MARC converted to RDF) is to "jumpstart" a new resource in Sinopia: to save the cataloger the time of re-typing or copying and pasting a bunch of information that already exists. Another use case: institutions want to take their converted MARC records, and add to (enhance) them.
(See [Requirements for Cloning/Deriving/Reusing/ in Sinopia](https://docs.google.com/document/d/18mrYqgMWJYokkCFcLWO0UPSlTBH3m2vkzWSXAPT4Uzk/) which has use cases. NOTE: we are not promising to meet all use cases in that requirements doc)

Scope and approach: The success criteria was defined as copying Share-VDE data. Another important use case is Discogs data. We will limit to those two sources, but hope to design something that could conceivably work for other external sources (via QA) later. General approach: load what we can, display the rest

Copy/derive elements:
- user "has" a Share-VDE (or Discogs) record (whether the record is selected in Search, or from a lookup in the Editor, or either, is TBD; **initially we want to make this work by pasting a record into the Load tab, as proof of concept, a way to illuminate challenges of this feature**)
- [x] ask user which Resource Template they want to copy it into (prototype on Load tab) (parent of #258)
- [x] copy matching data into Resource Template and if there are statements that don't "fit", tell the user and show those "remainder" statements in a useful way. (prototype from Load tab. parent of #259)

after above works, need to add:
- [x] way for user to select item from Search and copy/derive it (see Astrid's design ; not ticketed yet)

Discogs use case is expected to be an easier case of above; the data is consistent, and there exists a Resource Template (CornellSinatra45:Work) that fits the data, so there should not be a "remainder"

RELATED
- copying a Sinopia-created resource to start a new one is covered in #263 

OUT OF SCOPE
- copying/deriving from more than one "thing" at a time / aka batch loading
- selecting an item from a lookup field on the Editor tab, and launching a copy from there. Some workflows assumed this, but the workflow could be modified to start on Search tab instead.
- copying external data into an **existing** resource (though there is a use case for this, Michelle to ticket so we will have it recorded)
- Automatic syncing of Sinopia data with external sources (i.e., for use case of enhancing a Share-VDE record, we are not keeping track of which Share-VDE "thing" the statements come from, nor are we exporting the enhanced resource back to Share-VDE)

**Comment by michelleif** [comment]
also covers Discogs use case

**Comment by michelleif** [comment]
Note: looking back at original success criteria for Sinopia WC#1, copying Sinopia data to start a new description was not one of the criteria. Don't know if this is an oversight, or if this feature is low priority, or not needed. In any case you can already copy a Sinopia description to start a new one, by previewing and then loading the data.
